### ISSUE TITLE
Toc numbering is weird when using `defaults: numbered: true`

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/sphinx-external-toc#47] opened 2021-06-24 04:26 UTC
When I use 
```
defaults:
  numbered: true
```

globally in `_toc.yml`, some of the files are not numbered. And this changes with the number of times I run the build. 

The screenshot is when I ran the build the first time:
<img width="254" alt="Screen Shot 2021-06-24 at 2 20 06 pm" src="https://user-images.githubusercontent.com/6542997/123202068-484dc900-d4f7-11eb-9f7b-0ada05f97072.png">

The warnings I got during the build:

<img width="1365" alt="Screen Shot 2021-06-24 at 2 25 35 pm" src="https://user-images.githubusercontent.com/6542997/123202490-0c673380-d4f8-11eb-9152-6912bf6abfbc.png">

**Comment by mmcky** [comment] 2021-07-01 10:34
duplicate of #45

**Closed by mmcky** 2021-07-01 10:34 UTC
